// <auto-generated />
using HTT.Test.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HTT.Test.Database.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20250910110103_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HTT.Test.Database.DataModels.ProductCategoryDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Электроника"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Одежда"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Книги"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Спорт"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Мебель"
                        });
                });

            modelBuilder.Entity("HTT.Test.Database.DataModels.ProductDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Смартфон"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Ноутбук"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Name = "Футболка"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Джинсы"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Name = "Программирование на C#"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Name = "Война и мир"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Name = "Наушники"
                        });
                });

            modelBuilder.Entity("HTT.Test.Database.DataModels.ProductDataModel", b =>
                {
                    b.HasOne("HTT.Test.Database.DataModels.ProductCategoryDataModel", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HTT.Test.Database.DataModels.ProductCategoryDataModel", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
